name: languages
description: A Flutter app to learn languages
version: 1.0.0+21

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  dahttp: ^3.3.1
  dafluta: ^5.1.1
  wakelock: ^0.6.2
  flutter_tts: ^3.7.0
  dropdown_search: ^5.0.6
  json_annotation: ^4.1.0
  shared_preferences: ^2.1.2

  flutter:
    sdk: flutter

dev_dependencies:
  daassets: ^1.3.2
  daunused: ^1.3.0
  dapublock: ^1.0.1
  build_runner: ^2.1.11
  daincrementer: ^1.2.0
  json_serializable: ^6.7.0
  flutter_launcher_icons: ^0.13.1

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/launcher/launcher.png'